syntax = "proto3";

package datakeeper;
option go_package = "github.com/Fuonder/datakeeper/proto";


service GophKeeper {
  // Регистрация пользователя
  rpc Register (RegisterRequest) returns (RegisterResponse);

  // Аутентификация пользователя
  rpc Authenticate (AuthenticateRequest) returns (AuthenticateResponse);

  // Загрузка данных для пользователя
  rpc GetData (GetDataRequest) returns (GetDataResponse);

  // Обновление данных
  rpc UpdateData (UpdateDataRequest) returns (UpdateDataResponse);

  // Удаление данных
  rpc DeleteData (DeleteDataRequest) returns (DeleteDataResponse);

  // Передача файла
  rpc UploadFile (stream FileChunk) returns (UploadFileResponse);

  // Загрузка файла
  rpc DownloadFile (DownloadFileRequest) returns (stream FileChunk);
}

message RegisterRequest {
  string login = 1;
  string password = 2;
}

message RegisterResponse {
  string jwt_token = 1; // Токен для пользователя
  string error_message = 2; // Сообщение об ошибке, если регистрация не удалась
}

message AuthenticateRequest {
  string login = 1;
  string password = 2;
}

message AuthenticateResponse {
  string jwt_token = 1; // Токен для пользователя
  string error_message = 2; // Сообщение об ошибке, если аутентификация не удалась
}

message GetDataRequest {
  string jwt_token = 1;
}

message GetDataResponse {
  repeated LoginData logins = 1;
  repeated TextData texts = 2;
  repeated CreditCardData cards = 3;
  repeated FileData files = 4;  // Файлы с именами и типами
}

message LoginData {
  string service_name = 1;
  string login = 2;
  string password_hash = 3;
  string metadata = 4; // Metadata
}

message TextData {
  string text = 1;
  string metadata = 2; // Metadata
}

message CreditCardData {
  string card_id = 1;
  string owner_name = 2;
  string metadata = 3; // Metadata
}

message FileData {
  string file_name = 1; // Имя файла
  string file_type = 2; // Тип файла (например, .pdf, .jpg)
}

message UpdateDataRequest {
  string jwt_token = 1;
  repeated LoginData logins = 2;
  repeated TextData texts = 3;
  repeated CreditCardData cards = 4;
  repeated FileData files = 5;
}

message UpdateDataResponse {
  bool success = 1;
  string message = 2;
}

message DeleteDataRequest {
  string jwt_token = 1;
  repeated int32 login_ids = 2;
  repeated int32 text_ids = 3;
  repeated int32 card_ids = 4;
  repeated int32 file_ids = 5;
}

message DeleteDataResponse {
  bool success = 1;
  string message = 2;
}

// Запрос на загрузку файла
message DownloadFileRequest {
  string file_name = 1;  // Имя файла
  string file_type = 2;  // Тип файла
}

// Ответ с частями файла
message FileChunk {
  string file_name = 1;   // Имя файла
  string file_type = 2;   // Тип файла
  bytes data = 3;         // Данные файла (часть)
}

// Ответ на загрузку файла
message UploadFileResponse {
  bool success = 1;       // Успех загрузки
  string message = 2;     // Сообщение о статусе
}
